project:
  type: website
  output-dir: _site

website:
  google-analytics: G-8ZTBW36K7F
  title: "DanPadLab"
  site-url: https://padpadpadpad.netlify.app
  repo-url: https://github.com/padpadpadpad/padpadpadpad_quarto
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts
      - href: software.qmd
        text: Software
      - href: publications.qmd
        text: Publications
      - icon: mortarboard-fill
        href: https://scholar.google.co.uk/citations?user=1DXIqF4AAAAJ&hl=en
      - icon: github
        href: https://github.com/padpadpadpad

comments:
  giscus:
    repo: padpadpadpad/padpadpadpad_quarto
      
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

