---
title: "Parallel evolution of Pseudomonas aeruginosa phage resistance and virulence loss in response to phage treatment in vivo and in vitro"
type: "article"
author: "Meaghan Castledine, Daniel Padfield, Pawel Sierocinski, Jesica Soria Pascual, Adam Hughes, Lotta Mäkinen, Ville-Petri Friman, Jean-Paul Pirnay, Maya Merabishvili, Daniel De Vos, Angus Buckling"
year: "2022"
publication: "eLife"
preprint: "https://doi.org/10.1101/2021.09.06.459069"
doi: "https://doi.org/10.7554/eLife.73679"
code: "https://github.com/mcastledine96/Parallel_evolution_phage_resistance_virulence_trade-offs_invivo_invitro"
data: "https://www.ebi.ac.uk/ena/browser/view/PRJEB47945?show=reads"
toc: false
comments: false
---

## Citation

Castledine, M., Padfield, D., Sierocinski, P., Pascual, J. S., Hughes, A., Mäkinen, L., Friman, V.P., Pirnay, J.P., Merabishvili, M., De Vos, D., & Buckling, A. (2022). Parallel evolution of *Pseudomonas aeruginosa* phage resistance and virulence loss in response to phage treatment in vivo and in vitro. **Elife**, *11*, e73679.

## Abstract

With rising antibiotic resistance, there has been increasing interest in treating pathogenic bacteria with bacteriophages (phage therapy). One limitation of phage therapy is the ease at which bacteria can evolve resistance. Negative effects of resistance may be mitigated when resistance results in reduced bacterial growth and virulence, or when phage coevolves to overcome resistance. Resistance evolution and its consequences are contingent on the bacteria-phage combination and their environmental context, making therapeutic outcomes hard to predict. One solution might be to conduct ‘in vitro evolutionary simulations’ using bacteria-phage combinations from the therapeutic context. Overall, our aim was to investigate parallels between in vitro experiments and in vivo dynamics in a human participant. Evolutionary dynamics were similar, with high levels of resistance evolving quickly with limited evidence of phage evolution. Resistant bacteria—evolved in vitro and in vivo—had lower virulence. In vivo, this was linked to lower growth rates of resistant isolates, whereas in vitro phage resistant isolates evolved greater biofilm production. Population sequencing suggests resistance resulted from selection on de novo mutations rather than sorting of existing variants. These results highlight the speed at which phage resistance can evolve in vivo, and how in vitro experiments may give useful insights for clinical evolutionary outcomes.
