---
title: "Community coalescence: an eco-evolutionary perspective"
type: "article"
author: "Meaghan Castledine, Pawel Sierocinski, Daniel Padfield, Angus Buckling"
year: "2020"
publication: "Philosophical Transactions of the Royal Society B"
doi: "https://doi.org/10.1098/rstb.2019.0252"
toc: false
comments: false
---

## Citation

Castledine, M., Sierocinski, P., Padfield, D., & Buckling, A. (2020). Community coalescence: an eco-evolutionary perspective. Philosophical Transactions of the Royal Society B, **375(1798)**, 20190252.

## Abstract

Community coalescence, the mixing of different communities, is widespread throughout microbial ecology. Coalescence can result in approximately equal contributions from the founding communities or dominance of one community over another. These different outcomes have ramifications for community structure and function in natural communities, and the use of microbial communities in biotechnology and medicine. However, we have little understanding of when a particular outcome might be expected. Here, we integrate existing theory and data to speculate on how a crucial characteristic of microbial communities—the type of species interaction that dominates the community—might affect the outcome of microbial community coalescence. Given the often comparable timescales of microbial ecology and microevolution, we explicitly consider ecological and evolutionary dynamics, and their interplay, in determining coalescence outcomes.
