---
title: "Bacteriophage resistance increases bacterial productivity by shifting population growth dynamics in the soil bacterium Variovorax sp"
type: "article"
author: "Meaghan Castledine, Daniel Padfield, Rai Lewis, Angus Buckling"
year: "2024"
publication: "bioRxiv"
preprint: "https://www.biorxiv.org/content/10.1101/2024.03.07.583923v1.abstract"
open_access: ""
doi: ""
code: ""
data: ""
toc: false
comments: false
---

## Citation

Castledine, M., **Padfield, D.**, Lewis, R., & Buckling, A. (2024). Bacteriophage resistance increases bacterial productivity by shifting population growth dynamics in the soil bacterium *Variovorax* sp. *bioRxiv*, 2024-03.

## Abstract

Bacteriophages can be important drivers of bacterial densities, and therefore microbial community composition and function. In response to phage infection, bacteria can evolve resistance while phage can reciprocally evolve to increase infectivity. Coevolutionary arms-races between bacteria and phage have been studied in many model systems and in pairs isolated from natural samples. However, how multiple bacteria-phage pairs coevolve simultaneously within a community is poorly understood. Here, we examine how three pairs of coexisting soil bacteria (*Ochrobactrum* sp., *Pseudomonas* sp., and *Variovorax* sp.) evolve with three species-specific bacteriophages over eight weeks of experimental evolution, both as host-parasite pairs in isolation and as a mixed community. Coevolution was very limited, with two phages going extinct after two weeks and *Ochrobactrum* phage increasing in infectivity without comparable reciprocal increases in bacterial resistance. One surprising finding was that *Variovorax* sp. increased in density following phage extinction, above that of no-phage controls. We examined the mechanisms behind this density increase through common garden experiments, growth curves, supernatant assays, and sequencing. Our results showed that this density increase resulted from genetic changes and was associated with phage resistance. Growth curves demonstrated that phage resistance shifted population growth curves such that density was higher in the death-phase. That resistance to lytic phage can improve host densities has implications for wider ecology and phage therapy where lytic phages are presumed to have negative effects on their hosts.
