---
title: "Temperature-dependent changes to host–parasite interactions alter the thermal performance of a bacterial host"
type: "article"
author: "Daniel Padfield, Meaghan Castledine, Angus Buckling"
year: "2020"
publication: "ISME"
open_access: "https://ore.exeter.ac.uk/repository/handle/10871/39738"
doi: "https://doi.org/10.1038/s41396-019-0526-5"
code: "https://github.com/padpadpadpad/Padfield_2019_ISME_bact_phage_temperature"
data: "https://doi.org/10.5281/zenodo.3492192"
toc: false
comments: false
---

## Citation

Padfield, D., Castledine, M., & Buckling, A. (2020). Temperature-dependent changes to host–parasite interactions alter the thermal performance of a bacterial host. **The ISME Journal**, *14(2)*, 389-398.

## Abstract

Thermal performance curves (TPCs) are used to predict changes in species interactions, and hence, range shifts, disease dynamics and community composition, under forecasted climate change. Species interactions might in turn affect TPCs. Here, we investigate how temperature-dependent changes in a microbial host–parasite interaction (the bacterium *Pseudomonas fluorescens*, and its lytic bacteriophage, SBWΦ2) changes the host TPC and the ecological and evolutionary mechanisms underlying these changes. The bacteriophage had a narrower thermal tolerance for infection, with their critical thermal maximum ~6 ºC lower than those at which the bacteria still had high growth. Consequently, in the presence of phage, the host TPC changed, resulting in a lower maximum growth rate. These changes were not just driven by differences in thermal tolerance, with temperature-dependent costs of evolved resistance also playing a major role: the largest cost of resistance occurred at the temperature at which bacteria grew best in the absence of phage. Our work highlights how ecological and evolutionary mechanisms can alter the effect of a parasite on host thermal performance, even over very short timescales.

