---
title: "Macroevolutionary dynamics in micro-organisms: generalists give rise to specialists across biomes in the ubiquitous bacterial phylum Myxococcota"
type: "article"
author: "Daniel Padfield, Suzanne Kay, Rutger Vos, Christopher Quince, Michiel Vos"
year: "2024"
publication: "bioRxiv"
preprint: "https://www.biorxiv.org/content/10.1101/2023.09.26.559479v1.abstract"
open_access: ""
doi: ""
code: "https://github.com/padpadpadpad/myxo_diversification"
data: ""
toc: false
comments: false
---

## Citation

Padfield, D., Kay, S., Vos, R., Quince, C., & Vos, M. (2023). Macroevolutionary dynamics in micro-organisms: generalists give rise to specialists across biomes in the ubiquitous bacterial phylum Myxococcota. bioRxiv, 2023-09.

## Abstract

Prokaryotes dominate the Tree of Life, but our understanding of the macroevolutionary processes generating this diversity is still limited. Habitat transitions are thought to be a key driver of prokaryote diversity. However, relatively little is known about how prokaryotes successfully transition and persist across environments, and how these processes might vary between biomes and lineages. Here, we investigate biome transitions and specialisation in natural populations of a focal bacterial phylum, the *Myxococcota*, sampled across a range of replicated soils and freshwater and marine sediments in Cornwall (UK). By targeted deep sequencing of the protein-coding gene rpoB, we found >2000 unique *Myxococcota* lineages, with the majority (77%) being biome specialists and with only <5% of lineages distributed across the salt barrier. Discrete character evolution models revealed that specialists in one biome rarely transitioned into specialists in another biome. Instead, evolved generalism mediated transitions between biome specialists. State-dependent diversification models found variation in speciation rates across the tree, but this variation was independent of biome association or specialisation. These results were robust to phylogenetic uncertainty, assumed amounts of missing phylogenetic information, and different levels of species delineation. Overall, our results are consistent with a “jack-of-all-trades” trade-off where generalists suffer a cost in any individual environment, resulting in rapid evolution of niche specialists and shed light on how bacteria could transition between biomes. 

