---
title: The reality of a weekend caring for my partner with severe ME.
description: |
  A brief description of how poorly Soph is in March 2024, and what it is like to help care for her for a couple of days.
author: Daniel Padfield
date: "03/20/2023"
date-modified: last-modified
categories: 
  - ME
  - Carer
image: ""
execute:
  message: false
  warning: false
  fig.align: "center"
draft: true
---

# Introduction

You may know me. You may not. I am Daniel Padfield, a microbial ecologist and carer. I live in Cornwall and my partner of 11 years is called Sophia Galpin. She lives in Cheltenham with her family and has very severe ME. She has been getting steadily worse for around 10 years, and is now bedbound in constant neuropathic pain. I visit every three weeks for 3 to 4 days.

The pain and suffering she gets through is very difficult to describe, but I have decided to try and give a glimpse of what it was in a typical day of caring for her. This is my account, of how it feels to watch her, of how I see her suffering. I am trying again to document this because right now, she cannot tell the world about what she is going through. Right now she cannot speak very well. Cannot text in full sentences. Cannot write. 

All in all, Soph sees people for ~1 hour a day. She sleeps for ~1 or 2 hours a night. So for >20 hours a day, she lies in her bed. Fighting. Surviving. Severe ME is relentless.

*A warning that this account is going to be very sad.*

# A (typical) day caring for Soph

## 07:15 wake up

## 11:40 Sophs breakfast

## 13:50 Sophs lunch

## 15:00 Chocolate

## 17:00 Drink

## 18:20 Soup

## 19:30 Time

At 7:30, I get an emoji 🤘🏻, asking me to come up. I walk in and take her glasses off her side table and clean them in the hallway. I help her take her sunglasses off (she has light sensitivity and wears these in the day) and put on her glasses. I lie next to her, but I cannot touch her. We have not hugged for several years due to her full body neuropathic pain. Instead I place my arm over her chest and allow her to hold it with her left hand. Her right hand holds onto her phone holder (she has had worsening vertigo for several years).

I go downstairs and bring up her chocolate, vegan spread cheese, and oat milk. Soph recently went off one of her evening food items, but she is so stubborn to maintain ehr calories that she has started eating began cheese. I go back up. Time to help her undress. I used to describe this as like the electric buzz game at the arcade. The one where if you touch the metal, the circuit is complete and the game buzzes, and you lose. It is now MUCH worse than that. 

## 21:40 Bed time

After I say good night, I go to bed. I can hear her screaming in pain through two doors. We cannot go in to comfort her. We cannot touch her. We cannot help her. She spends all day bottling stuff up to try and save us from the worst of it. And now she lets it all out. Ridiculously, I can still fall asleep. I can still sleep a solid 8 hours. I call it my mundane superpower.

# A double life

Two days later, I am in work. I read through a manuscript draft. Answer some emails. Sit in a meeting about lab space. Twenty four hours ago I was holding a cup for Soph to drink soup. The contrast is stark.